version: "3.7"

services:
    app:
        image: node:12-alpine
        command: sh -c "yarn install && yarn run dev"
        ports:
            - 3000:3000
        working_dir: /app_bkp
        volumes:
            - ./:/app_bkp
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: todos
    mysql:
        image: mysql:5.7
        #restart: always
        volumes:
            # - ./resources/docker-sql:/docker-entrypoint-initdb.d
            # cat resources/docker-sql/init.sql | docker exec -i 39d446ec8bd8 /usr/bin/mysql -u root --password=secret todos
            - todo-mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: todos
volumes:
    todo-mysql-data: